AWSTemplateFormatVersion:
  '2010-09-09'
Description: EC2
Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0453ec754f44f9a4a
    us-west-1:
      AMI: ami-0583d8c7a9c35822c
Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: all sg
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref MySecurityGroup
      ImageId: !FindInMap
        - RegionMap
        - !Ref "AWS::Region"
        - AMI
Outputs:
  InstanceId:
    Value: !Ref MyEC2Instance
  PublicIp:
    Value: !GetAtt MyEC2Instance.PublicIp





